// This file is autogenerated. Changes will be overwritten.
#include "6YEA5652QU/moc_inputzone.cpp"
#include "6YEA5652QU/moc_mainpage.cpp"
#include "6YEA5652QU/moc_outputzone.cpp"
#include "6YEA5652QU/moc_synwindow.cpp"
#include "6YEA5652QU/moc_widget.cpp"
